theme: jekyll-theme-hacker

domain: nsu-fit-programming.github.io
url: https://nsu-fit-programming.github.io

title:       "Программирование"
description: "Теория по курсу \"Программирование\" ФИТ НГУ"
copyright:   "© Группа 21212"

header_pages:
  - index.md