title:       "Структуры данных"
description: "Система непересекающихся множеств, операции определения представителя множества и объединения двух множеств. Реализация СНМ с помощью дерева с рангом и сжатием путей"
copyright:   "© Группа 21212"

header_pages:
  - index.md
