title:       "Алгоритмы"
description: "Алгоритмы поиска значения в списке и добавления значения в список для списков, реализованных через массив значений элементов и через структуры с указателями."
copyright:   "© Группа 21212"

header_pages:
  - index.md
